language: node_js
node_js:
- 10
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: y0aPB0m3MN/Hs4LK0VpBRTYH4bAyoSqwhmEOZxb+jt0XqK8UKo4qZ3XlLiu0pjsTC7sbMUIYIgKcyMdoYf68lbJzysaVNbUh/DGIJBNmzYORXzsHB5nsptx3x77e/AszR4JzPGfcI4CkVpk4Dqw4yUyOtWlSYr/dofMDYbOQ4Wru31SbOlhvF42GdNaCV9fbiBwyBdDHRIsr9m6ZArKq0fX5Ij9GUcgj9L3LqZQvDB6SaTwmN9n9MIUFyqOm9/NS6zJz5aZUTaKI7HH3540uokf89VfifxCXI1ym15g2V2XUgVtyzzN88N3R9qiCjpdiilM0MXkamsS01QH+APZlo2VYr1qgPnhEyKEfCRXNE19q/rvoe69Y6w7u9322IRd/fqwQ+vCX1fHlzqLG/TwcjH97VeHLLaIQ46+6occH0uWWyT2C3Nnd54JrfnsnLvJOqpV0cOjzlmyPaTTFkbASpfLUM2O8MAkSYK/INpWJxEk9z1/2XBW4Dtyt2DvnLh6hBnEA+6VhlQ75J3sUQneDBvmHUxwqt0VTF3Q+IF8FD/SIrN074sDzQtDYToYsBObuL7sRLYVdUF6oKlObkc78fXEZvxrkVkj5DBaydYcZTEr0T0T5jhnpvqxx5TF1HRrWu2YnPnOGDB5mIvEWEOrw80dZtI4MjQW/zHj07yL1N50=
  on:
    tags: true
    repo: noflo/noflo-runtime-postmessage
